FROM python:3.11

WORKDIR /app/app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app/

EXPOSE 8501

ENV PYTHONPATH=/app/app

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]